server/djangoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL

    # path for about view
    path('about/', views.about, name='about'),
    # path for contact us view
    path('contact/', views.contact, name='contact'),
    # path for registration
    path('registration/', views.registration_request, name='registration'),
    # path for login
    path('login/', views.login_request, name='login'),
    # path for logout
    path('logout/', views.logout_request, name='logout'),
    path('dealer/<int:dealer_id>/', views.get_dealer_details, name='dealer_details'),
    path('dealer/<int:dealer_id>/add-review', views.add_review, name='dealer_add_review'),
    path(route='', view=views.get_dealerships, name='index'),

    # path for dealer reviews view

    # path for add a review view

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangoapp/models.py
from django.db import models
from django.utils.timezone import now


# Create your models here.

class CarMake(models.Model):
    name = models.CharField(null=False, max_length=30)
    description = models.CharField(max_length=1000)

    def __str__(self):
        return "Name: " + self.name + "," + \
               "Description: " + self.description

class CarModel(models.Model):
    name = models.CharField(null=False, max_length=30)
    carmake = models.ForeignKey(CarMake, on_delete=models.CASCADE)
    dealer_id = models.IntegerField()
    SEDAN = 'sedan'
    SUV = 'suv'
    WAGON = 'wagon'
    OTHER = 'other'
    CAR_TYPE_CHOICES = [
        (SEDAN, 'Sedan'),
        (SUV, 'SuV'),
        (WAGON, 'Wagon'),
        (OTHER, 'Other')
    ]
    car_type = models.CharField(
        max_length=10,
        choices=CAR_TYPE_CHOICES,
        default=OTHER,
    )
    year = models.DateField()

    def __str__(self):
        return "Name: " + self.name + "," + \
               "Type: " + self.car_type + "," + \
               "Year: " + self.year.strftime("%Y")


# <HINT> Create a plain Python class `CarDealer` to hold dealer data
class CarDealer:
    def __init__(self, dealership):
        for key,value in dealership.items():
            setattr(self, key, value)

    def __str__(self):
        return "Dealer name: " + self.full_name

# <HINT> Create a plain Python class `DealerReview` to hold review data
class DealerReview:
    def __init__(self, review, sentiment):
        for key,value in review.items():
            setattr(self, key, value)
        self.sentiment = sentiment

    def __str__(self):
        return "Dealer name: " + self.full_name

server/djangoapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from .models import CarMake, CarModel
from .restapis import get_dealers_from_cf, get_dealer_by_id_from_cf, get_dealers_by_state, get_dealer_reviews_from_cf, post_request
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from datetime import datetime
import logging
import json

# Get an instance of a logger
logger = logging.getLogger(__name__)


# Create your views here.


# Create an `about` view to render a static about page
def about(request):
    context = {}
    context['title'] = 'About us'
    return render(request, 'djangoapp/about.html', context)


# Create a `contact` view to return a static contact page
def contact(request):
    context = {}
    context['title'] = 'Contact us'
    return render(request, 'djangoapp/contact.html', context)

# Create a `login_request` view to handle sign in request
def login_request(request):
    context = {}
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('djangoapp:index')
        else:
            context['message'] = "Invalid username or password."
            return render(request, 'djangoapp/index.html', context)
    else:
        return render(request, 'djangoapp/index.html', context)

# Create a `logout_request` view to handle sign out request
def logout_request(request):
    logout(request)
    return redirect('djangoapp:index')

# Create a `registration_request` view to handle sign up request
def registration_request(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'djangoapp/registration.html', context)
    elif request.method == 'POST':
        # Check if user exists
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            User.objects.get(username=username)
            user_exist = True
        except:
            logger.error("New user")
        if not user_exist:
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                            password=password)
            login(request, user)
            return redirect("djangoapp:index")
        else:
            context['message'] = "User already exists."
            return render(request, 'djangoapp/registration.html', context)

# Update the `get_dealerships` view to render the index page with a list of dealerships
def get_dealerships(request):
    context = {}
    context['title'] = 'Dealership'
    if request.method == "GET":
        # Get dealers from the URL
        dealerships = get_dealers_from_cf()
        context['dealerships'] = dealerships
        # Return a list of dealer short name
        return render(request, 'djangoapp/index.html', context)

# Create a `get_dealer_details` view to render the reviews of a dealer
def get_dealer_details(request, dealer_id):
    context = {}
    context['title'] = 'Dealership Details'
    if request.method == "GET":
        context['dealership'] = get_dealer_by_id_from_cf(dealer_id)
        context['reviews'] = get_dealer_reviews_from_cf(dealer_id)
        return render(request, 'djangoapp/dealer_details.html', context)

# Create a `add_review` view to submit a review
def add_review(request, dealer_id):
    if request.method == "GET":
        context = {}
        context['dealer_id'] = dealer_id
        context['username'] = request.user.first_name + " " + request.user.last_name
        context['cars'] = CarModel.objects.all()

        return render(request, 'djangoapp/add_review.html', context)
    if request.method == "POST":
        car_id = request.POST.get('car')
        car = CarModel.objects.get(id=car_id)
        purchase = request.POST.get('purchase')

        review = {}
        review['time'] = datetime.utcnow().isoformat().split('T')[0]
        review['dealership'] = dealer_id
        review['review'] = request.POST.get('review')
        review['name'] = request.POST.get('username')
        review['purchase_date'] = request.POST.get('purchasedate')
        review['car_model'] = car.name
        review['car_year'] = car.year.year
        review['car_make'] = car.carmake.name

        if purchase == 'on':
            review['purchase'] = True
        else:
            review['purchase'] = False

        if request.user and request.user.is_authenticated:
            json_payload = { "review": review }
            post_request('https://2e35c4b8.eu-gb.apigw.appdomain.cloud/api/review', json_payload, dealerId=dealer_id)
            return redirect("djangoapp:dealer_details", dealer_id)
        else:
            return redirect("djangoapp:dealer_details", dealer_id)

server/djangoapp/templates/djangoapp/about.html
{% extends "djangoapp/index.html" %}
{% block content %}
        <h1>
            Welcome to Best Cars dealership, home to the best cars in North America. We sell domestic and imported cars at reasonable prices.
        </h1>
    </body>
    {% endblock %}

server/djangoapp/templates/djangoapp/add_review.html
{% extends "djangoapp/index.html" %}
{% block content %}
<script type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css" />
<form action="{% url 'djangoapp:dealer_add_review' dealer_id %}" method="post">
    <div class="container" style="width: 80vw;">
        {% csrf_token %}
        <h1>Add Review</h1>
        <hr>
        <div class="form-group">
            <label for="username"><b>User Name</b></label>
            <input type="text" class="form-control" value="{{ username }}" disabled name="username">
        </div>
        <div class="form-group">
            <label for="car"><b>Select Car</b></label>
            <select name="car" id="car" class="form-select" required>
                {% for car in cars %}
                <option selected value={{car.id}}>{{car.name}}-{{car.make.name}}-{{ car.year|date:"Y" }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" name="purchase" id="purchase">
            <label class="form-check-label" for="purchasecheck"><b>Car purchased</b></label>
        </div>
        <div class="form-group">
            <label for="purchasedate"><b>Purchase date</b></label>
            <input class="date-own form-control w-25" type="text" name="purchasedate" id="purchasedate">
        </div>
        <div class="form-group">
            <label for="review"><b>Review Text</b></label>
            <textarea class="form-control" id="review" name="review" rows="2" required></textarea>
        </div>
        <button class="btn btn-primary" type="submit">Post review</button>
    </div>
    </div>
</form>
<script type="text/javascript">
    $('.date-own').datepicker({
        format: 'mm/dd/yyyy'
    });
</script>
{% endblock %}

server/djangoapp/templates/djangoapp/contact.html
{% extends "djangoapp/index.html" %}

{% block content %}
<div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
    <h6 class="text-uppercase fw-bold mb-4">
      Contact
    </h6>
    <p><i class="fas fa-home me-3"></i> Some Adress</p>
    <p>
      <i class="fas fa-envelope me-3"></i>
      info@example.com
    </p>
    <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
    <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
  </div>
  {% endblock %}

server/djangoapp/templates/djangoapp/dealer_details.html
{% extends "djangoapp/index.html" %}
{% block content %}
<div class="card m-4">
  <div class="card-header">
    <div class="d-inline float-left">
      <h3>{{dealership.full_name}}</h3>
    </div>
    {% if user.is_authenticated %}
    <div class="d-inline float-right"><button class="btn btn-primary"
        onclick="window.location.href = `{% url 'djangoapp:dealer_add_review' dealership.id %}`">Add review</button>
    </div>
    {% endif %}
  </div>
  <ul class="list-group list-group-flush">
    {% for review in reviews %}
    <li class="list-group-item">
      <div class="row">
        <div class="col-1 d-flex">
          <span
            class="material-icons m-auto {% if review.sentiment == 'positive' %} text-success {% elif review.sentiment == 'negative' %} text-danger {% else %} text-warning {% endif %} ">
            circle
          </span>
        </div>
        <div class="col ">
          <h5 class="card-title">
            {{ review.car_make }} - {{ review.car_model }} - {{ review.car_year }}
          </h5>
          <div class="row">
            <div class="col-3">Review date: {{ review.time }} </div>
            <div class="col-3">Car purchased: {{ review.purchase }}
              {% if review.purchase == True %}
              - {{review.purchase_date}}
              {% endif %} </div>
          </div>
          <hr>
          <p class="card-text m-4">{{ review.review }}</p>
        </div>
      </div>
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

server/djangoapp/templates/djangoapp/footer.html
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
    
  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Best Dealership
          </h6>
          <p>
            Find an rate your favourit Dealer
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Links
          </h6>
          <p>
            <a href="{% url 'djangoapp:about' %}" class="text-reset">About us</a>
          </p>
          <p>
            <a href="{% url 'djangoapp:contact' %}" class="text-reset">Contact</a>
          </p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright: Best Dealership
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

server/djangoapp/templates/djangoapp/head.html
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script
        src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
</head>

server/djangoapp/templates/djangoapp/index.html
<!DOCTYPE html>
<html>
{% include 'djangoapp/head.html' %}

<body>
    <!--Add a nav bar here -->
    {% include 'djangoapp/navbar.html' %}

    {% block content %}
    <div style="width: 90vw; margin: auto">
        <table class="table table-hover" id="table" data-filter-control="true">
            <thead class="thead-dark">
                <tr>
                    <th data-field="id">ID</th>
                    <th data-field="name">Name</th>
                    <th data-field="city">City</th>
                    <th data-field="address">Adress</th>
                    <th data-field="zip">Zip</th>
                    <th data-field="state" data-filter-control="select">State</th>
                </tr>
            </thead>
            <tbody>
                {% for dealer in dealerships %}
                <tr style="cursor: pointer;">
                    <td>{{dealer.id}}</td>
                    <td><a href="{% url 'djangoapp:dealer_details' dealer.id %}">{{dealer.full_name}}</a></td>
                    <td>{{dealer.city}}</td>
                    <td>{{dealer.address}}</td>
                    <td>{{dealer.zip}}</td>
                    <td>{{dealer.state}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script>
        $(function () {
            $('#table').bootstrapTable()
        })
    </script>
    {% endblock %}
</body>
{% include 'djangoapp/footer.html' %}

</html>

server/djangoapp/templates/djangoapp/navbar.html
<nav class="navbar navbar-light bg-light mb-4">
    <div class="container-fluid">
        <a href="{% url 'djangoapp:index' %}">
        <span class="navbar-brand mb-0 h1">Best Dealership</span>
        </a>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'djangoapp:about' %}">About</a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li>
                <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                <a class="btn btn-link" href="{% url 'djangoapp:logout' %}">Logout</a>
            </li>
            {% else %}
            <li>
                <form class="form-inline" action="{% url 'djangoapp:login' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" class="form-control {% if message %} is-invalid {% endif%}" placeholder="Username" name="username" >
                        <input type="password" class="form-control {% if message %} is-invalid {% endif%}" placeholder="Password" name="psw" >
                        <button class="btn btn-primary" type="submit">Login</button>
                        <a class="btn btn-link" href="{% url 'djangoapp:registration' %}">Sign Up</a>
                    </div>
                </form>
                {% if message %} <p class="text-danger">{{ message }}</p>{% endif%}
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

server/djangoapp/templates/djangoapp/registration.html
{% extends "djangoapp/index.html" %}
{% block content %}
        <form action="{% url 'djangoapp:registration' %}" method="post">
            <div class="container"> <!--Style root div with .container class -->
                {% csrf_token %}
                <h1>Sign Up</h1>
                <hr>
                <div class="form-group"> <!--Style second div with .form-group class -->
                    <label for="username"><b>User Name</b></label>
                    <input type="text" class="form-control" placeholder="Enter User Name: " name="username" required> <!--Style input with .form-control class -->
                    <label for="firstname"><b>First Name</b></label>
                    <input type="text" class="form-control" placeholder="Enter First Name: " name="firstname" required> <!--Style input with .form-control class -->
                    <label for="lastname"><b>Last Name</b></label>
                    <input type="text" class="form-control" placeholder="Enter Last Name: " name="lastname" required> <!--Style input with .form-control class -->
                    <label for="psw"><b>Password</b></label>
                    <input type="password" class="form-control" placeholder="Enter Password: " name="psw" required> <!--Style input with .form-control class -->
                    {% if message %}
                    <div class="alert alert-warning"> <!--Style the message paragraph with .alert and .alert-warning class -->
                        {{ message }}
                    </div>
                    {% endif %}
                    <button class="btn btn-primary" type="submit">Sign up</button> <!--Style button with .btn and .btn-primary class -->
                </div>
            </div>
        </form>
{% endblock %}